name: Git Branching Strategy

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  Code-Copy:
    runs-on: self-hosted

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          path: 'main'
