name: Git Branching Strategy

on:
  pull_request:
    branches: uat
    types: [closed]
  workflow_dispatch:

jobs:
  Code-Copy:
    runs-on: self-hosted

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          path: 'uat'
